<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CashTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cash')->insert([
            [
                'nomeproduto' => 'Cash Vendido Por Pix',
                'nomecliente' => 'Vitiello',
                'valor' => 0,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => 44.5,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Up RD',
                'nomecliente' => 'RD',
                'valor' => 100,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Maça[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Arco Composto[4] - custo sp -7% , medio+8%, sombrio +6%, sp max -68',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 7,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Hidra',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 10,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Faca[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Medusa',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 6,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Malha[1]',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 10,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Maça[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bota[1]',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bastão[1] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Drops 2x',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 12,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Poring Noel',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bota[1]',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Elmo',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Poring Noel 4x',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 12,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Broche',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Faca[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],

            [
                'nomeproduto' => 'Maça[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bota[1]',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bastão[1] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Bastão[1] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Broche',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '11x Armas Lixo RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 14,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Chapéu de Bufão',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '2x Carta Gargula',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 4,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '1x Carta Pesadelo',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Luva de Puxada',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 6,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Luva de Puxada',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 6,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Katana[1] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '2x Maça[4] RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 4,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Clava RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Guisarme RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Glaive',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Stiletto RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '2x Ovos Rank C',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 8,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Stiletto RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '5x Carta Poring Noel',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 20,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Zipper',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Goblin',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Flora',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Ovo de Pesadelo',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 10,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Anolian',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 10,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Arco de Caça +6',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Chapéu Fedorento',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Botas[1]',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Bathory ',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 12,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Stiletto RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => '2x Carta Poring Noel',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Tritao',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 8,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Pupa',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Ecudo Espelhado',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Lavadeira',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 3,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Carta Argiope + Minha parte na carta Caimbra',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 5,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Stiletto RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 1,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Main Gauche RO',
                'nomecliente' => 'Vendido no Mercador',
                'valor' => 2,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
            [
                'nomeproduto' => 'Botas[1] + Brinco',
                'nomecliente' => 'Drake Cadman',
                'valor' => 5,
                'nomeprodutoterceiro' => '',
                'nometerceiro' => '',
                'valorterceiro' => null,
                'valortotal' => null,
            ],
        ]);
    }
}
